apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-coll-47a70170bd15456f8c4314e859b4f6d2-depl
  labels:
    app: product-coll-47a70170bd15456f8c4314e859b4f6d2
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-coll-47a70170bd15456f8c4314e859b4f6d2
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: product-coll-47a70170bd15456f8c4314e859b4f6d2
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: product-coll-47a70170bd15456f8c4314e859b4f6d2
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:product-coll-47a70170bd15456f8c4314e859b4f6d2
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping